### ISSUE TITLE
KeyError: 'raw_frame'

### ISSUE THREAD

**Issue by tonivss** [PUTvision/thermo-hardware-benchmark#7]
When executing the **Modek Training** I get the following Error:

**Exception has occurred: KeyError**
```
'raw_frame'  
  File "thermo/utils/model_utils.py", line 12, in check_model_prediction  
    raw_frame = np.array(config['dataset']["raw_frame"])  
  File "train.py", line 136, in train  
    count, output_frame = check_model_prediction(model, config)  
  File "train.py", line 170, in <module>  
    train()  
KeyError: 'raw_frame'
```

When calling the function `count, output_frame = check_model_prediction(model, config)` there appears to be no key `raw_frawe` in config.

**Comment by MatPiech** [comment]
Hi @tonivss!
I've added PR with updates for your issue. Could you change a branch and verify if these changes resolved your problem?

**Comment by MatPiech** [comment]
I will close that issue and merge PR. You can re-open it if you need to.
